# -*- coding: utf-8 -*-
"""Swiggy Sales Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y99sRr6_mlv6H48vrDNj_vUBkHnflJk_

#**Swiggy Sales Analysis**

**Import Libraries**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""**Import Data**"""

df = pd.read_excel(r"/content/swiggy_data.xlsx")

df

df.head()

df.tail()

"""**Metadata**"""

print("No.of Rows:",df.shape[0], "& No.of Columns:",df.shape[1])

df.info()

"""**Data Types**"""

df.dtypes

df.describe()

"""## **KPI's**

**Total Sales**
"""

total_sales = df["Price (INR)"].sum()
print("Total Sales (INR):",total_sales)

"""**Average Rating**"""

avg_rating = df["Rating"].mean()
print("Average rating:",round(avg_rating,2))

"""**Average Order Value**"""

avg_order_value = df["Price (INR)"].mean()
print("Average order value (INR) is :",round(avg_order_value,2))

"""**Ratings Count**"""

ratings_count = df["Rating Count"].sum()
print("Ratings Count:",ratings_count)

"""**Total Orders**"""

print("Total Orders:", len(df))

"""# **Charts** **Design**

**Monthly Sales Trend**
"""

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["YearMonth"] = df["Order Date"].dt.to_period("M").astype(str)

monthly_revenue = df.groupby("YearMonth")["Price (INR)"].sum().reset_index()

plt.figure()
plt.plot(monthly_revenue["YearMonth"], monthly_revenue["Price (INR)"],color="#FC8019",
    linewidth=2.5)
plt.xticks(rotation=45)
plt.xlabel("Month")
plt.ylabel("Total Sales (INR)")
plt.title("Monthly Revenue Trend")
plt.tight_layout()
plt.show()

"""**Daily Sales Trend**"""

df["DayName"] = pd.to_datetime(df["Order Date"]).dt.day_name()

daily_revenue = (df.groupby("DayName")["Price (INR)"]).sum().reindex(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])

plt.figure(figsize=(10,5))
plt.bar(daily_revenue.index, daily_revenue.values,color="#FC8019",
    edgecolor="#E86F00",
    linewidth=1
)
plt.xticks(rotation=30)
plt.xlabel("Day")
plt.ylabel("Total Sales (INR)")
plt.title("Daily Revenue Trend (Mon-Sun)")
plt.tight_layout()
plt.show()

"""**Total Sales by Food Type (Veg and Non-Veg)**"""

non_veg_keywords = [
    "chicken", "egg", "fish", "mutton", "prawn",
    "biryani", "kabab", "kebab", "non veg", "non-veg"
]

df["Food Category"] = np.where(
    df["Dish Name"].str.lower().str.contains("|".join(non_veg_keywords), na=False),
    "Non-Veg", "Veg"
)

food_revenue = (
    df.groupby("Food Category")["Price (INR)"].sum().reset_index()
)

fig = px.pie(
    food_revenue,
    values="Price (INR)",
    names="Food Category",
    hole=0.5,
    title="Revenue Contribution: Veg vs Non-Veg",
    color="Food Category",
    color_discrete_map={
        "Veg": "#2E7D32",
        "Non-Veg": "#FC8019"
    }
)

fig.update_traces(
    textinfo="percent+label",
    pull=[0.05,0]
)

fig.update_layout(
    height=500,
    margin=dict(t=60, b=40, l=40, r=40)
)

fig.show()

"""**Total Sales by States**"""

fig = px.bar(
    df.groupby("State", as_index=False)["Price (INR)"].sum()
      .sort_values("Price (INR)", ascending=False),
    x="Price (INR)",
    y="State",
    orientation="h",
    title="Revenue by State (INR)",
    color_discrete_sequence=["#FC8019"]  # Swiggy orange
)
fig.update_layout(height=600, yaxis=dict(autorange="reversed"))
fig.show()

"""**Quarterly Performance Summary**"""

df["Order_Date"] = pd.to_datetime(df["Order Date"])
df["Quarter"] = df["Order_Date"].dt.to_period("Q").astype(str)

quarterly_summary = (
    df.groupby("Quarter", as_index=False)
      .agg(
          Total_Sales=("Price (INR)", "sum"),
          Avg_Rating=("Rating", "mean"),
          Total_Orders=("Order_Date", "count")
      )
      .sort_values("Quarter")
)

quarterly_summary["Total_Sales"] = quarterly_summary["Total_Sales"].round(0)
quarterly_summary["Avg_Rating"] = quarterly_summary["Avg_Rating"].round(2)

quarterly_summary

"""**Top 5 Cities by Sales**"""

top_5_cities = (
    df.groupby("City")["Price (INR)"]
      .sum()
      .nlargest(5)
      .sort_values()
      .reset_index()
)

fig = px.bar(
    top_5_cities,
    x="Price (INR)",
    y="City",
    orientation="h",
    title="Top 5 Cities by Sales (INR)",
    color_discrete_sequence=["#FC8019"]  # Swiggy orange
)

fig.show()